name: terraform-apply-dev

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  apply-dev:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # để sau này có thể dùng OIDC assume role thay access keys

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials for DEV
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Init
        working-directory: infra/envs/dev
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: infra/envs/dev
        run: terraform apply -input=false -auto-approve
